In [1]:
import torch

In [2]:
import sklearn

In [40]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

### KNN algorithm

In [15]:
# About the dataset

In [4]:
irisdata=load_iris()


In [7]:
irisdata.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
irisdata['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
irisdata['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
irisdata['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
irisdata['data'][0]

array([5.1, 3.5, 1.4, 0.2])

In [16]:
irisdata['data'].shape

(150, 4)

In [18]:
irisdata['target'].shape

(150,)

*****

In [78]:
class KNN:
    
    def __init__(self,neighbours,distance):
        self.neighbours=neighbours
        self.distance=distance
        
    def fit(self,x,y):
        self.x_train=x
        self.y_train=y
    
    def predict(self,x_test):
        
        y_pred=[]
        
        for item in x_test:
            
            if self.distance=="euclidean":
                distance=np.linalg.norm(self.x_train-item,axis=1)
            
            elif self.distance=="manhattan":
                distance=np.sum(np.abs(self.x_train-item),axis=1)
            
            else:
                distance = np.power(np.sum(np.power(np.abs(self.x_train - x), self.distance), axis=1), 1/self.distance)
            
            
            nearest_indices=np.argsort(distance)[:self.neighbours]
            nearest_labels=self.y_train[nearest_indices]
            
            label= Counter(nearest_labels).most_common(1)[0][0]
            y_pred.append(label)
            
        return np.array(y_pred)
            
        

In [79]:
xtrain,xtest,ytrain,ytest=train_test_split(irisdata['data'],irisdata['target'],test_size=0.2,random_state=42)

In [80]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((120, 4), (30, 4), (120,), (30,))

In [83]:
knn=KNN(neighbours=5, distance="euclidean")

knn.fit(xtrain,ytrain)

ypred=knn.predict(xtest)

accuracy=accuracy_score(ypred,ytest)

print(accuracy)


1.0


****

### ROUGH WORK

In [ ]:
np.linalg.norm(self.X_train - x, axis=1)

In [34]:
knn.x_train[:3]

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4]])

In [33]:
xtest[0]

array([6.1, 2.8, 4.7, 1.2])

In [35]:
knn.x_train[:3]-xtest[0]

array([[-1.5,  0.8, -3.7, -1. ],
       [-0.4,  1.6, -3.2, -0.8],
       [ 0.6,  0.3, -0.3,  0.2]])

In [46]:
np.linalg.norm(knn.x_train[:3]-xtest[0], axis=1)

array([1.6643317 , 1.81383571, 4.9010203 , 1.29614814])

In [44]:
import math
math.sqrt(1.5*1.5+0.8**2+3.7**2+1)

4.192851058647326

In [47]:
np.sum(np.abs(knn.x_train[:3]-xtest[0]),axis=1)

array([7. , 6. , 1.4])

In [49]:
np.argsort([2,5,6,7,1])[:2]

array([4, 0])

In [51]:
from collections import Counter

In [58]:
Counter([1,1,1,2,3]).most_common(1)[0][0]

1